"""add_reservation_timeout_fields

Revision ID: 3688b32fba03
Revises: 0f1d38c6e030
Create Date: 2026-02-22 16:26:59.592132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3688b32fba03'
down_revision: Union[str, Sequence[str], None] = '0f1d38c6e030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('reserved_at', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('reserved_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'users', ['reserved_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'reserved_by_id')
    op.drop_column('items', 'reserved_at')
    # ### end Alembic commands ###
