"""add_multiple_images

Revision ID: edc494cb9146
Revises: ca1a7efd501a
Create Date: 2026-04-10 00:41:16.791117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc494cb9146'
down_revision: Union[str, Sequence[str], None] = 'ca1a7efd501a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_url_2', sa.String(length=500), nullable=True))
    op.add_column('items', sa.Column('image_url_3', sa.String(length=500), nullable=True))
    op.add_column('items', sa.Column('image_url_4', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('reservations_item_id_fkey'), 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(op.f('reservations_item_id_fkey'), 'reservations', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_column('items', 'image_url_4')
    op.drop_column('items', 'image_url_3')
    op.drop_column('items', 'image_url_2')
    # ### end Alembic commands ###
